MvcExamenEventos/Models/CategoriaEvento.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace MvcExamenEventos.Models
{
    public class CategoriaEvento
    {
        public int IdEvento { get; set; }
        public string Nombre { get; set; }
    }
}

MvcExamenEventos/Models/ErrorViewModel.cs
namespace MvcExamenEventos.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvcExamenEventos/Models/EventoExamen.cs
using System.ComponentModel.DataAnnotations.Schema;
using System.ComponentModel.DataAnnotations;

namespace MvcExamenEventos.Models
{
    public class EventoExamen
    {
        public int IdEvento { get; set; }
        public string Nombre { get; set; }
        public string Artista { get; set; }
        public int IdCategoria { get; set; }
        public string Imagen { get; set; }
    }
}

MvcExamenEventos/Models/KeysModel.cs
namespace MvcExamenEventos.Models
{
    public class KeysModel
    {
        public string MySql { get; set; }
        public string ApiEventos { get; set; }
        public string BucketName { get; set; }
        public string UrlBucket { get; set; }
    }
}

MvcExamenEventos/Controllers/EventosController.cs
using Microsoft.AspNetCore.Mvc;
using MvcExamenEventos.Models;
using MvcExamenEventos.Services;

namespace MvcExamenEventos.Controllers
{
    public class EventosController : Controller
    {
        private ServiceApiEventos service;
        

        public EventosController(ServiceApiEventos service)
        {
            this.service = service;
        }
        public async Task<IActionResult> Index()
        {
            List<EventoExamen> eventos = await this.service.GetEventosAsync();
            return View(eventos);
        }
        public async Task<IActionResult> Categorias()
        {
            List<CategoriaEvento> categorias = await this.service.GetCategoriasAsync();
            return View(categorias);
        }
        public async Task<IActionResult> EventosCategoria(int id)
        {
            List<EventoExamen> eventos = await this.service.GetEventosCategoriaAsync(id);
            return View(eventos);
        }
    }
}

MvcExamenEventos/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using MvcExamenEventos.Models;
using System.Diagnostics;

namespace MvcExamenEventos.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvcExamenEventos/Views/Eventos/Categorias.cshtml
@model List<CategoriaEvento>


<h1>Categorias</h1>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>
                ID EVENTO
            </th>
            <th>
                NOMBRE
            </th> 
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @item.IdEvento
                </td>
                <td>
                    @item.Nombre
                </td>  
                <td>
                    <a asp-controller="Eventos" asp-action="EventosCategoria" asp-route-id="@item.IdEvento" >Go to Events</a>
                </td>
            </tr>
        }
    </tbody>
</table>

MvcExamenEventos/Views/Eventos/EventosCategoria.cshtml
@model List<EventoExamen>

@{
    string UrlBucket = keysModel.UrlBucket;
}

<h1>Eventos por Categoria</h1>

@if (Model != null)
{
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>
                    ID EVENTO
                </th>
                <th>
                    NOMBRE
                </th>
                <th>
                    ARTISTA
                </th>
                <th>
                    IDCATEGORIA
                </th>
                <th>
                    IMAGEN
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @item.IdEvento
                    </td>
                    <td>
                        @item.Nombre
                    </td>
                    <td>
                        @item.Artista
                    </td>
                    <td>
                        @item.IdCategoria
                    </td>
                    <td>
                        <img src="@UrlBucket@item.Imagen" style="width:70px; height: 80px" />
                    </td>
                </tr>
            }
        </tbody>
    </table>
}
else
{
    <h1>No hay eventos</h1>
}

MvcExamenEventos/Views/Eventos/Index.cshtml
@model List<EventoExamen>

@{
    string UrlBucket = keysModel.UrlBucket;
}

<h1>Index</h1>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>
               ID EVENTO
            </th>
            <th>
               NOMBRE
            </th>
            <th>
                ARTISTA
            </th>
            <th>
                IDCATEGORIA
            </th>
            <th>
                IMAGEN
            </th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @item.IdEvento
            </td>
            <td>
                @item.Nombre
            </td>
            <td>
                @item.Artista
            </td>
            <td>
                @item.IdCategoria
            </td>
            <td>
                  <img src="@UrlBucket@item.Imagen" style="width:70px; height: 80px"/>
            </td>           
        </tr>
}
    </tbody>
</table>

MvcExamenEventos/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvcExamenEventos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvcExamenEventos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvcExamenEventos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MvcExamenEventos</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Eventos" asp-action="Index">Eventos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Eventos" asp-action="Categorias">Categorias</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - MvcExamenEventos - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>